export enum EventSubSubscriptionType {
    AUTOMOD_SETTINGS_UPDATE = "automod.settings.update",
    CHANNEL_BAN = "channel.ban",
    CHANNEL_CHAT_MESSAGE = "channel.chat.message",
    CHANNEL_FOLLOW = "channel.follow",
    CHANNEL_SUBSCRIBE = "channel.subscribe",
    CHANNEL_SUBSCRIPTION_MESSAGE = "channel.subscription.message",
    CHANNEL_UNBAN = "channel.unban",
    CHANNEL_UPDATE = "channel.update",
    CHANNEL_VIP_ADD = "channel.vip.add",
    CHANNEL_VIP_REMOVE = "channel.vip.remove",
    MESSAGE_DELETE = "channel.chat.message_delete",
    MODERATOR_ADD = "channel.moderator.add",
    MODERATOR_REMOVE = "channel.moderator.remove",
    STREAM_ONLINE = "stream.online",
    STREAM_OFFLINE = "stream.offline",
}